[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = [
  "chmod +x mvnw || true",
  "./mvnw clean package -DskipTests -B",
  "chmod +x start.sh || true"
]

[phases.start]
cmd = "./start.sh"

